In [30]:
import numpy as np

In [31]:
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
y=np.zeros(10)
y[5]=1
y

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [33]:
z=np.arange(10,50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [34]:
a=np.array([[0,1,3],[4,5,6],[7,8,1]])
a

array([[0, 1, 3],
       [4, 5, 6],
       [7, 8, 1]])

TypeError: only integer scalar arrays can be converted to a scalar index

In [35]:
a[np.nonzero(a)]

array([1, 3, 4, 5, 6, 7, 8, 1])

In [36]:
b = np.array([1,2,0,0,4,0])
b[np.nonzero(b)]

array([1, 2, 4])

In [43]:
c=np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
d=np.random.random((3,3,3))
d

array([[[0.65229471, 0.245265  , 0.55858521],
        [0.34082509, 0.11647869, 0.60590884],
        [0.8222671 , 0.15863501, 0.60909976]],

       [[0.67448334, 0.3977131 , 0.84143537],
        [0.9262484 , 0.97151659, 0.86550379],
        [0.82042527, 0.70813385, 0.62632531]],

       [[0.22397371, 0.17211879, 0.17076944],
        [0.49182238, 0.19772557, 0.49915883],
        [0.76336223, 0.97805285, 0.59403846]]])

In [53]:
e=np.random.random((10,10))
e

array([[0.5546342 , 0.73277194, 0.87320301, 0.40682648, 0.34843382,
        0.92466603, 0.58140087, 0.87230106, 0.98081803, 0.85794928],
       [0.81656434, 0.27790341, 0.84241874, 0.12818655, 0.85843108,
        0.91491332, 0.48369104, 0.86873731, 0.01901843, 0.46482633],
       [0.94454761, 0.65254311, 0.18671382, 0.60487944, 0.23293416,
        0.9216016 , 0.54328246, 0.97515715, 0.6674615 , 0.03859107],
       [0.30358662, 0.09424466, 0.5436665 , 0.13002551, 0.10463666,
        0.2166932 , 0.16842328, 0.56650583, 0.9759459 , 0.18059046],
       [0.91788151, 0.37440525, 0.17589001, 0.20073516, 0.30052102,
        0.06009937, 0.55406632, 0.56064804, 0.79279796, 0.41903522],
       [0.82274521, 0.01177648, 0.81982974, 0.38772193, 0.79063861,
        0.07316102, 0.98868542, 0.59013026, 0.80462372, 0.95702482],
       [0.11395083, 0.78301245, 0.71858272, 0.11644167, 0.73996436,
        0.38105411, 0.83683512, 0.25088249, 0.59428444, 0.84580993],
       [0.43742682, 0.78943872, 0.2015477

In [54]:
np.amax(e)

0.9886854234360404

In [55]:
np.amin(e)

0.011776479543166296

In [56]:
f=np.random.random(30)
f

array([0.21457536, 0.40894285, 0.74606078, 0.74491625, 0.77987524,
       0.35963138, 0.04214496, 0.28060171, 0.31220275, 0.53396607,
       0.31413128, 0.3939713 , 0.73943702, 0.07689819, 0.44600055,
       0.52828626, 0.56944057, 0.45414536, 0.67695964, 0.18319838,
       0.28395491, 0.4486843 , 0.88272029, 0.15528477, 0.00609155,
       0.53805881, 0.01608249, 0.212042  , 0.07100555, 0.53245959])

In [58]:
np.mean(f)

0.3983923397459861

In [68]:
g=np.diag([0,1,2,3,4])
g

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [78]:
h=np.random.random((5,5))
h

array([[0.43443225, 0.3810852 , 0.69732251, 0.40289006, 0.05502692],
       [0.03550248, 0.40006541, 0.80654925, 0.572962  , 0.01886027],
       [0.27505422, 0.23425006, 0.84762319, 0.17116626, 0.08241248],
       [0.44169949, 0.20468666, 0.79869661, 0.70761178, 0.29399536],
       [0.61580297, 0.92914202, 0.87601238, 0.81895582, 0.13925985]])

## Normalize Matrix

In [89]:
np.mean(h)
np.std(h)

h_normiert=

NameError: name 'random' is not defined

In [79]:
hmax,hmin = h.max(), h.min()
h=(h-hmin)/(hmax-hmin)
h

array([[0.45653116, 0.39792617, 0.74533213, 0.42188014, 0.03973127],
       [0.01828247, 0.41877709, 0.86532437, 0.60871453, 0.        ],
       [0.28144467, 0.23661881, 0.9104466 , 0.16731741, 0.06981597],
       [0.46451466, 0.20414161, 0.85669776, 0.75663553, 0.30225267],
       [0.65577795, 1.        , 0.94163385, 0.87895375, 0.13226627]])

In [93]:
np.intersect1d([1,2,3,4],[2,3,4,5],[3,4,5,6])


array([2, 3, 4])

In [101]:
g=np.random.random((10,10))
g.sort()
g

array([[0.2568809 , 0.26292187, 0.28669987, 0.36858134, 0.54720032,
        0.70191947, 0.81535149, 0.82061967, 0.87463713, 0.92611994],
       [0.03443412, 0.11584295, 0.29489216, 0.29805025, 0.39888804,
        0.40468518, 0.80299339, 0.83412189, 0.93610561, 0.99350926],
       [0.01957472, 0.04651628, 0.15220486, 0.15347426, 0.20336185,
        0.76549872, 0.77682774, 0.88721814, 0.91499274, 0.96347417],
       [0.0804924 , 0.1394089 , 0.16144138, 0.29032576, 0.4746861 ,
        0.59671311, 0.60321059, 0.72753876, 0.82242327, 0.84858869],
       [0.08884097, 0.24803504, 0.29536726, 0.36320474, 0.39335499,
        0.62675926, 0.72995611, 0.76643958, 0.82579105, 0.99760118],
       [0.18158411, 0.25104522, 0.26495762, 0.30399771, 0.5295867 ,
        0.60868454, 0.72288888, 0.78440681, 0.88485728, 0.88639188],
       [0.21026435, 0.25482074, 0.2708302 , 0.27575153, 0.46202474,
        0.65615961, 0.6819287 , 0.76452787, 0.77262577, 0.922383  ],
       [0.42581807, 0.4348056 , 0.5881184

In [141]:
i=np.random.random((10,10))
i[(: 10)]=0

SyntaxError: invalid syntax (2012231566.py, line 2)

In [143]:
k=np.random.random((5,5))
l=k-k.mean(axis=1, keepdims=True)
l

array([[-0.27276455,  0.04656059,  0.2906218 , -0.37380771,  0.30938987],
       [-0.3856256 ,  0.02662027, -0.1995942 ,  0.2809106 ,  0.27768893],
       [ 0.48532862, -0.21479853,  0.11712949, -0.12112887, -0.26653071],
       [-0.187104  , -0.1009409 , -0.01556734,  0.0140908 ,  0.28952144],
       [-0.38336758, -0.05278784,  0.36031545,  0.12360239, -0.04776243]])

In [160]:
Z = np.arange(10000)
np.random.shuffle(Z)
n=5
sorted_index_z=np.argsort(z)

In [161]:
sorted_z = z[sorted_index_z]

In [175]:
sorted_z[-n: ]

array([45, 46, 47, 48, 49])

In [163]:
print("{} largest value:".format(n),
      sorted_z[0])

5 largest value: 10


In [174]:
m=np.random.random((5,3))
print(np.where(m > 4),m**2,m)

(array([], dtype=int64), array([], dtype=int64)) 0 [[0.46590969 0.368901   0.69534699]
 [0.9306955  0.27225961 0.76871741]
 [0.25125971 0.37708405 0.38230902]
 [0.02129368 0.12819903 0.74995339]
 [0.22114121 0.84144248 0.34490508]]
